### ISSUE TITLE
got "Incompatible Version" problem when connect with "macOS Big Sur" version

### ISSUE THREAD

**Issue by hillyson** [nwtgck/piping-vnc-web#2]
the connection will be failured

**Comment by nwtgck** [comment]
Thank you for the report. Do you use the following built-in VNC client in macOS?

<img width="598" alt="image" src="https://user-images.githubusercontent.com/10933561/127736060-8e9500ca-bc2b-43ea-a91c-e190141b3332.png">

**Comment by nwtgck** [comment]
Piping VCN is highly based on noVNC project. Unfortunately, the project says

> No, I'm afraid not. macOS simply requires some non-standard VNC client. We have no way of knowing what they need unless they publish some specifications.

from: https://github.com/novnc/noVNC/issues/1522#issuecomment-789831962

**Comment by nwtgck** [comment]
@hillyson Hi,

noVNC 1.4.0 supports this feature. So I merged the 1.4.0 changes: https://github.com/nwtgck/piping-vnc-web/commit/8d5f5fdfb4ce155e4da07004e908ce296f34aa6f. It is already available in <https://piping-vnc.nwtgck.org>.

Here is a demo video:

https://user-images.githubusercontent.com/10933561/235641495-43018e51-2225-4ee0-a940-3543b7469067.mp4

The feature should be implemeted by https://github.com/novnc/noVNC/pull/1590.
